# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mtr.sync.lib.exceptions
import mtr.sync.settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='mtr.sync:name')),
                ('cell', models.CharField(blank=True, max_length=1000, verbose_name='mtr.sync:cell')),
                ('value', models.CharField(blank=True, max_length=1000, verbose_name='mtr.sync:value')),
            ],
            options={
                'verbose_name_plural': 'mtr.sync:contexts',
                'verbose_name': 'mtr.sync:context',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.BigIntegerField(blank=True, default=-1, null=True, verbose_name='mtr.utils:position')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='mtr.sync:name')),
                ('attribute', models.CharField(max_length=255, verbose_name='mtr.sync:model attribute')),
                ('skip', models.BooleanField(default=False, verbose_name='mtr.sync:skip')),
                ('update', models.BooleanField(default=True, verbose_name='mtr.sync:update')),
                ('find', models.BooleanField(default=False, verbose_name='mtr.sync:find')),
                ('set_filter', models.CharField(blank=True, choices=[('not', 'mtr.sync:Not create or update instance if empty cell')], max_length=255, verbose_name='mtr.sync:set filter type')),
                ('set_value', models.CharField(blank=True, max_length=255, verbose_name='mtr.sync:set value')),
                ('find_filter', models.CharField(blank=True, choices=[('icontains', 'icontains'), ('contains', 'contains'), ('iexact', 'iexact'), ('exact', 'exact'), ('in', 'in'), ('gt', 'gt'), ('gte', 'gte'), ('lt', 'lt'), ('lte', 'lte'), ('not', 'not')], default='exact', max_length=255, verbose_name='mtr.sync:find filter type')),
                ('find_value', models.CharField(blank=True, max_length=255, verbose_name='mtr.sync:find value')),
                ('converters', models.CharField(blank=True, max_length=255, verbose_name='mtr.sync:converters')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'mtr.sync:fields',
                'verbose_name': 'mtr.sync:field',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.BigIntegerField(blank=True, default=-1, null=True, verbose_name='mtr.utils:position')),
                ('message', models.TextField(max_length=10000, verbose_name='mtr.sync:message')),
                ('step', models.PositiveSmallIntegerField(choices=[(0, 'mtr.sync:import data'), (1, 'mtr.sync:unexpected error')], default=1, verbose_name='mtr.sync:step')),
                ('input_position', models.CharField(blank=True, max_length=10, verbose_name='mtr.sync:input position')),
                ('input_value', models.TextField(blank=True, max_length=60000, null=True, verbose_name='mtr.sync:input value')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'mtr.sync:Error'), (1, 'mtr.sync:Info')], default=0, verbose_name='mtr.sync:type')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'mtr.sync:messages',
                'verbose_name': 'mtr.sync:message',
                'ordering': ('position',),
            },
            bases=(models.Model, mtr.sync.lib.exceptions.ErrorChoicesMixin),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'mtr.sync:Export'), (1, 'mtr.sync:Import')], db_index=True, default=0, verbose_name='mtr.sync:action')),
                ('buffer_file', models.FileField(blank=True, db_index=True, upload_to=mtr.sync.settings.get_buffer_file_path, verbose_name='mtr.sync:file')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'mtr.sync:Error'), (1, 'mtr.sync:Running'), (2, 'mtr.sync:Success')], default=1, verbose_name='mtr.sync:status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='mtr.sync:started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='mtr.sync:completed at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mtr.sync:updated at')),
            ],
            options={
                'verbose_name_plural': 'mtr.sync:reports',
                'verbose_name': 'mtr.sync:report',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='mtr.sync:name')),
                ('buffer_file', models.FileField(blank=True, db_index=True, upload_to=mtr.sync.settings.get_buffer_file_path, verbose_name='mtr.sync:file')),
                ('description', models.TextField(blank=True, null=True, verbose_name='mtr.sync:description')),
            ],
            options={
                'verbose_name_plural': 'mtr.sync:sequences',
                'verbose_name': 'mtr.sync:sequence',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_in_db', models.DateTimeField(auto_now_add=True, null=True, verbose_name='mtr.utils:created at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='mtr.utils:created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mtr.utils:updated at')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'mtr.sync:Export'), (1, 'mtr.sync:Import')], db_index=True, default=0, verbose_name='mtr.sync:action')),
                ('name', models.CharField(blank=True, help_text='mtr.sync:Small description of operation', max_length=100, verbose_name='mtr.sync:name')),
                ('start_row', models.PositiveIntegerField(blank=True, help_text='mtr.sync:Reading or writing start index (including itself)', null=True, verbose_name='mtr.sync:start row')),
                ('end_row', models.PositiveIntegerField(blank=True, help_text='mtr.sync:Reading or writing end index (including itself)', null=True, verbose_name='mtr.sync:end row')),
                ('model', models.CharField(blank=True, help_text='mtr.sync:Choose database model if action need it', max_length=255, verbose_name='mtr.sync:model')),
                ('show_in_quick_menu', models.BooleanField(default=False, verbose_name='mtr.sync:show in quick menu list')),
                ('processor', models.CharField(default='XlsxProcessor', help_text='mtr.sync:Choose file type', max_length=255, verbose_name='mtr.sync:format')),
                ('worksheet', models.CharField(blank=True, help_text='mtr.sync:Page name of sheet book', max_length=255, verbose_name='mtr.sync:worksheet page')),
                ('include_header', models.BooleanField(default=True, help_text='mtr.sync:Check it if you need to write field names in export or skip it in import', verbose_name='mtr.sync:include header')),
                ('filename', models.CharField(blank=True, help_text='mtr.sync:Custom filename for export', max_length=255, verbose_name='mtr.sync:custom filename')),
                ('buffer_file', models.FileField(blank=True, db_index=True, help_text='mtr.sync:File for import action', upload_to=mtr.sync.settings.get_buffer_file_path, verbose_name='mtr.sync:file')),
                ('dataset', models.CharField(blank=True, help_text='mtr.sync:Custom registered dataset if you import or export data from different source, for example network or ftp server', max_length=255, verbose_name='mtr.sync:dataset')),
                ('data_action', models.CharField(blank=True, help_text='mtr.sync:What will be done with data, for example, create or some custom opeartion eg. download image from server', max_length=255, verbose_name='mtr.sync:data action')),
                ('filter_dataset', models.BooleanField(default=True, help_text='mtr.sync:Check it if you have custom queryset and want to filter from querystring, for example from admin button', verbose_name='mtr.sync:filter custom dataset')),
                ('filter_querystring', models.CharField(blank=True, help_text='mtr.sync:Querystring from admin or other source, if you choose import action this params will be used for updating!', max_length=255, verbose_name='mtr.sync:querystring')),
                ('language', models.CharField(blank=True, choices=[('de', 'German'), ('en', 'English')], help_text='mtr.sync:Activates language before action, for example if you want you have modeltranslation app and you need to export or import only for choosed language', max_length=255, verbose_name='mtr.sync:language')),
                ('hide_translation_fields', models.BooleanField(default=True, help_text="mtr.sync:If you don't want to create _lang field settings and dublicate in attribute list, handy if you using modeltranslation", verbose_name='mtr.sync:Hide translation prefixed fields')),
                ('create_fields', models.BooleanField(default=True, help_text='mtr.sync:Automaticaly creates all settings for model fields', verbose_name='mtr.sync:Create settings for fields')),
                ('populate_from_file', models.BooleanField(default=False, help_text='mtr.sync:Read start row, end row and first worksheet page from given file', verbose_name='mtr.sync:Populate settings from file')),
                ('include_related', models.BooleanField(default=True, help_text="mtr.sync:Include ForeignKey and ManyToManyField fields when using 'create fields' option", verbose_name='mtr.sync:Include related fields')),
                ('edit_attributes', models.BooleanField(default=False, help_text='mtr.sync:If you want to add custom attributes for custom action, by checking this option, you can edit attributes', verbose_name='mtr.sync:Edit field attributes')),
            ],
            options={
                'verbose_name_plural': 'mtr.sync:settings',
                'verbose_name': 'mtr.sync:settings',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='sequence',
            name='settings',
            field=models.ManyToManyField(related_name='sequences', to='mtr_sync.Settings', verbose_name='mtr.sync:settings'),
        ),
        migrations.AddField(
            model_name='report',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mtr_sync.Settings', verbose_name='mtr.sync:settings'),
        ),
        migrations.AddField(
            model_name='message',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mtr_sync.Report'),
        ),
        migrations.AddField(
            model_name='field',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mtr_sync.Settings', verbose_name='mtr.sync:settings'),
        ),
        migrations.AddField(
            model_name='context',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='mtr_sync.Settings', verbose_name='mtr.sync:settings'),
        ),
    ]
