# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('surname', models.TextField(verbose_name='Apellidos')),
                ('birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('id_number', models.TextField(verbose_name='DNI/NIE')),
                ('ss_number', models.TextField(verbose_name='Tarjeta sanitaria')),
                ('address_street', models.TextField(verbose_name='Dirección')),
                ('address_locality', models.TextField(verbose_name='Localidad')),
                ('address_region', models.TextField(verbose_name='Provincia')),
                ('address_country', models.TextField(verbose_name='País')),
                ('phone_number', models.TextField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('comment', models.TextField(verbose_name='Observaciones')),
                ('health_warnings', models.TextField(verbose_name='Observaciones médicas')),
            ],
        ),
    ]
