# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20161027_1659'), ('core', '0003_auto_20161103_1905'), ('core', '0004_persongroup'), ('core', '0005_auto_20161106_1924'), ('core', '0006_auto_20161106_1926'), ('core', '0007_enrolment_created'), ('core', '0008_auto_20161212_1928'), ('core', '0009_membership'), ('core', '0010_auto_20161214_1913'), ('core', '0011_auto_20161219_1826'), ('core', '0012_membership_person'), ('core', '0013_person_mobile_number'), ('core', '0014_membership_membership_status')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(verbose_name='Nombre grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_membership', models.TextField(blank=True, default='', verbose_name='Modalidad')),
                ('id_card_status', models.TextField(blank=True, default='', verbose_name='DNI/NIE')),
                ('ss_card_status', models.TextField(blank=True, default='', verbose_name='Tarjeta sanitaria')),
                ('photo_status', models.TextField(blank=True, default='', verbose_name='Foto')),
                ('dpa_status', models.TextField(blank=True, default='', verbose_name='LOPD')),
                ('payment_status', models.TextField(blank=True, default='', verbose_name='Estado del pago')),
                ('membership_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cuota de membresia')),
                ('card_status', models.TextField(blank=True, default='', verbose_name='Estado del carnet')),
                ('membership_status', models.TextField(blank=True, default='', verbose_name='Estado de socio')),
            ],
            options={
                'verbose_name': 'Membresia',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Nombre')),
                ('surname', models.TextField(verbose_name='Apellidos')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('id_number', models.TextField(blank=True, default='', verbose_name='DNI/NIE')),
                ('ss_number', models.TextField(blank=True, default='', verbose_name='Tarjeta sanitaria')),
                ('address_street', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('address_locality', models.TextField(blank=True, default='', verbose_name='Localidad')),
                ('address_region', models.TextField(blank=True, default='', verbose_name='Provincia')),
                ('address_country', models.TextField(blank=True, default='', verbose_name='País')),
                ('phone_number', models.TextField(blank=True, default='', verbose_name='Teléfono')),
                ('mobile_number', models.TextField(blank=True, default='', verbose_name='Teléfono móvil')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('health_warnings', models.TextField(blank=True, default='', verbose_name='Observaciones médicas')),
            ],
            options={
                'verbose_name': 'Persona',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together=set([('person', 'group')]),
        ),
    ]
