# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0014_membership_membership_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_status', models.TextField(blank=True, default='', verbose_name='DNI/NIE')),
                ('ss_card_status', models.TextField(blank=True, default='', verbose_name='Tarjeta sanitaria')),
                ('photo_status', models.TextField(blank=True, default='', verbose_name='Foto')),
                ('dpa_status', models.TextField(blank=True, default='', verbose_name='LOPD')),
                ('card_status', models.TextField(blank=True, default='', verbose_name='Estado del carnet')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
            options={
                'verbose_name': 'Datos de socio',
            },
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
