# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_country',
            field=models.TextField(blank=True, default='', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_locality',
            field=models.TextField(blank=True, default='', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_region',
            field=models.TextField(blank=True, default='', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_street',
            field=models.TextField(blank=True, default='', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='person',
            name='health_warnings',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones médicas'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.TextField(blank=True, default='', verbose_name='DNI/NIE'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.TextField(blank=True, default='', verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ss_number',
            field=models.TextField(blank=True, default='', verbose_name='Tarjeta sanitaria'),
        ),
    ]
