# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161027_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(verbose_name='Nombre grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona'},
        ),
    ]
