# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170109_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_membership', models.TextField(blank=True, default='', verbose_name='Modalidad')),
                ('payment_status', models.TextField(blank=True, default='', verbose_name='Estado del pago')),
                ('membership_fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cuota de membresia')),
                ('membership_status', models.TextField(blank=True, default='', verbose_name='Estado de socio')),
            ],
            options={
                'verbose_name': 'Membresía',
            },
        ),
        migrations.AddField(
            model_name='personmembership',
            name='membership',
            field=models.ForeignKey(default='196e1d2b-3ca4-45bb-848f-cdb6428f9c0e', on_delete=django.db.models.deletion.CASCADE, to='core.Membership'),
            preserve_default=False,
        ),
    ]
