# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lack_of_sexual_offenses_date_certificate', models.DateField(default=None, null=True, verbose_name='Fecha de emisión del Certificado de Delitos de Naturaleza Sexual')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
            options={
                'verbose_name': 'Voluntario',
            },
        ),
    ]
