# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_persongroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonGroup',
            new_name='Enrolment',
        ),
        migrations.AlterModelOptions(
            name='enrolment',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
    ]
