# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custodian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('father', 'Padre'), ('mother', 'Madre'), ('legal', 'Tutor')], max_length=32, verbose_name='Tipo')),
                ('minor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recipient')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
            options={
                'verbose_name': 'Padre, madre, tutor',
            },
        ),
    ]
