# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161106_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de inscripción'),
            preserve_default=False,
        ),
    ]
