# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='personmembership',
            name='person',
        ),
        migrations.DeleteModel(
            name='PersonMembership',
        ),
    ]
