# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161212_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.TextField(blank=True, default='', verbose_name='id')),
                ('name', models.TextField(blank=True, default='', verbose_name='Nombre')),
                ('surname', models.TextField(blank=True, default='', verbose_name='Apellidos')),
                ('role', models.TextField(blank=True, default='', verbose_name='Rol')),
                ('group', models.TextField(blank=True, default='', verbose_name='Grupo')),
                ('phone_number', models.TextField(blank=True, default='', verbose_name='Teléfono')),
                ('mobile_number', models.TextField(blank=True, default='', verbose_name='Movil')),
                ('email', models.TextField(blank=True, default='', verbose_name='email')),
                ('id_card', models.TextField(blank=True, default='', verbose_name='DNI/NIE')),
                ('ss_card', models.TextField(blank=True, default='', verbose_name='Tarjeta sanitaria')),
                ('photo', models.TextField(blank='True', default='', verbose_name='Foto')),
                ('DPA', models.TextField(blank=True, default='', verbose_name='LOPD')),
                ('membership_fee', models.TextField(blank=True, default='', verbose_name='Cuota de membresia')),
                ('membership_payment', models.TextField(blank=True, default='', verbose_name='Pago de membresia')),
                ('done_idmembership', models.TextField(blank=True, default='', verbose_name='Carnet para entregar')),
                ('delivered_idmembership', models.TextField(blank=True, default='', verbose_name='Carnet entragado')),
            ],
            options={
                'verbose_name': 'Membresia',
            },
        ),
    ]
