# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170320_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Fotografía'),
        ),
    ]
