# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170320_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='dpa_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id_card_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ss_card_status',
        ),
        migrations.AddField(
            model_name='person',
            name='dpa_status',
            field=models.TextField(blank=True, default='', verbose_name='LOPD'),
        ),
        migrations.AddField(
            model_name='person',
            name='id_card_status',
            field=models.TextField(blank=True, default='', verbose_name='DNI/NIE'),
        ),
        migrations.AddField(
            model_name='person',
            name='ss_card_status',
            field=models.TextField(blank=True, default='', verbose_name='Tarjeta sanitaria'),
        ),
    ]
