# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.TextField(default='', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='uuid',
            field=models.TextField(blank=True, default='', verbose_name='id Membresia'),
        ),
    ]
