# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161214_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='DPA',
            new_name='dpa_status',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='id_card',
            new_name='id_card_status',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='ss_card',
            new_name='ss_card_status',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='delivered_idmembership',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='done_idmembership',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='email',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='membership_payment',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='uuid',
        ),
        migrations.AddField(
            model_name='membership',
            name='card_status',
            field=models.TextField(blank=True, default='', verbose_name='Estado del carnet'),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_status',
            field=models.TextField(blank=True, default='', verbose_name='Estado del pago'),
        ),
        migrations.AddField(
            model_name='membership',
            name='photo_status',
            field=models.TextField(blank=True, default='', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='membership',
            name='type_of_membership',
            field=models.TextField(blank=True, default='', verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cuota de membresia'),
        ),
    ]
