# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='members', verbose_name='Subir foto'),
        ),
    ]
