# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170409_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='recipient',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='core.Recipient'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='group',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='core.Group'),
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='person',
        ),
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together=set([('recipient', 'group')]),
        ),
    ]
