# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170330_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default=None, upload_to='members', verbose_name='Fotografía'),
        ),
    ]
