# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161219_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
            preserve_default=False,
        ),
    ]
