# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_membership_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile_number',
            field=models.TextField(blank=True, default='', verbose_name='Teléfono móvil'),
        ),
    ]
