# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_volunteer_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='authorized_signature',
            field=models.TextField(blank=True, default='', verbose_name='Firma autorización'),
        ),
        migrations.AddField(
            model_name='custodian',
            name='emergency_contact',
            field=models.TextField(blank=True, default='', verbose_name='Contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='person',
            name='dpa_authorization',
            field=models.TextField(blank=True, default='', verbose_name='LOPD'),
        ),
        migrations.AddField(
            model_name='person',
            name='id_photocopy',
            field=models.TextField(blank=True, default='', verbose_name='Fotocopia DNI/NIE'),
        ),
        migrations.AddField(
            model_name='person',
            name='ss_photocopy',
            field=models.TextField(blank=True, default='', verbose_name='Fotocopia Seguridad Social'),
        ),
    ]
