# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_person_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='brother_sister',
            field=models.IntegerField(blank=True, default='', verbose_name='Hermanos'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='estudies',
            field=models.TextField(blank=True, default='', verbose_name='Estudios'),
        ),
    ]
