# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_person_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_status',
            field=models.TextField(blank=True, default='', verbose_name='Estado de socio'),
        ),
    ]
