# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_volunteer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bursary',
            field=models.TextField(blank=True, default='', verbose_name='Beca'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='Authorize_photo',
            field=models.TextField(blank=True, default='', verbose_name='Autoriza foto'),
        ),
    ]
