# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170425_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='Authorize_photo',
            new_name='authorize_photo',
        ),
    ]
