# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='estudies',
        ),
        migrations.AddField(
            model_name='recipient',
            name='courses',
            field=models.CharField(blank=True, choices=[('4EI', '4 Educacion Infantil'), ('5EI', '5 Educacion Infantil'), ('6EI', '6 Educacion Infantil'), ('1EP', '1 Educacion Primaria'), ('2EP', '2 Educacion Primaria'), ('3EP', '3 Educacion Primaria'), ('4EP', '4 Educacion Primaria'), ('5EP', '5 Educacion Primaria'), ('6EP', '6 Educacion Primaria'), ('1ESO', '1 Educación Secundaria Obligatoria'), ('2ESO', '2 Educación Secundaria Obligatoria'), ('3ESO', '3 Educación Secundaria Obligatoria'), ('4ESO', '4 Educación Secundaria Obligatoria'), ('1BACH', '1 Bachillerato'), ('2BACH', '2 Bachillerato'), ('FP', 'Formación Profesional'), ('CARRERA', 'Carrera Universitaria')], default='', max_length=32, verbose_name='Estudios'),
        ),
    ]
