# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(verbose_name='Nombre actividad')),
                ('event_start', models.DateField(verbose_name='Fecha inicio')),
                ('event_end', models.DateField(verbose_name='Fecha fin')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Actividades',
            },
        ),
    ]
