# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Actividad'},
        ),
    ]
