# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Actividad'},
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='school',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Centro de estudios'),
        ),
    ]
