# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170427_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='college',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Centro de estudios'),
        ),
    ]
