# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_recipient_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='college',
            new_name='school',
        ),
    ]
