# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_group_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='school',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Centro de estudios'),
        ),
    ]
