# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170524_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='groups',
        ),
    ]
