# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_group_project'),
        ('core', '0021_auto_20170525_0941'),
    ]

    operations = [
    ]
