# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170526_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='category',
            field=models.CharField(blank=True, choices=[('child', 'Infantil'), ('juvenile', 'Juvenil')], default='', max_length=32, verbose_name='Tipo'),
        ),
    ]
