# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170907_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodian',
            name='category',
            field=models.CharField(blank=True, choices=[('father', 'Padre'), ('mother', 'Madre'), ('legal', 'Tutor')], default='', max_length=32, verbose_name='Tipo'),
        ),
    ]
