# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170907_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotografía'),
        ),
    ]
