# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 18:13
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models._get_file_path, verbose_name='Fotografía'),
        ),
    ]
