language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
cache: pip
env:
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
matrix:
    exclude:
        -
            python: 3.3
            env: DJANGO=1.9
        -
            python: 3.5
            env: DJANGO=1.7
install:
    - python setup.py develop
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r tests/requirements/python2.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r tests/requirements/python3.txt; fi
    - pip install "django==$DJANGO" --upgrade
script: fab test:coverage
